load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "qtl",
    hdrs = [
	"apply_tuple.h",
	"qtl_asio.hpp",
	"qtl_async.hpp", 
	"qtl_common.hpp",
	"qtl_database_pool.hpp",
	"qtl_mysql.hpp",
	"qtl_mysql_pool.hpp",
	"qtl_odbc.hpp",
	"qtl_odbc_pool.hpp",
	"qtl_postgres.hpp",
	"qtl_postgres_pool.hpp",
	"qtl_sqlite.hpp",
	"qtl_sqlite_pool.hpp",
    ],
    visibility = [
	"//visibility:public",
    ],
)

